apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-hostpath

spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: tmp-vol
          mountPath: /my-mnt
  volumes:
    - name: tmp-vol
      hostPath:
        path: /tmp/test-vol
