apiVersion: batch/v1
kind: Job
metadata:
  name: printenv

spec:
  template:
    metadata:
      name: printenv
    spec:
      containers:
        - name: ospod
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in {1..100}; do sleep 1;env; done"
      restartPolicy: Never