apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mypodcontainer
      image: nginx
      volumeMounts:
        - mountPath: "/etc/foo"
          name: foo
          readOnly: true

  volumes:
    - name: foo
      secret:
        secretName: mysecret