apiVersion: v1
kind: Pod
metadata:
  name: mypod-with-env
spec:
  restartPolicy: Never
  containers:
    - name: mypodcontainer
      image: nginx
      env:
        - name: MY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username

        - name: MY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
